version: '3.5'
services:
  db:
    image: postgres:latest
    container_name: rinha2023_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    command: -c config_file=/etc/postgresql.conf
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./migrations:/docker-entrypoint-initdb.d
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: 11
          memory: 10GB

  api1: &api
    image: rinha_sql:latest
    environment:
      - PORT=6969
    restart: always
    container_name: rinha_sql_1
    depends_on:
      db:
        condition: service_healthy
    network_mode: host
    # deploy:
      # resources:
        # limits:
          # cpus: .04
          # memory: 900MB
  
  api2:
    <<: *api
    environment:
      - PORT=4200
    container_name: rinha_sql_2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    # deploy:
      # resources:
        # limits:
          # cpus: .01
          # memory: 200MB

