version: '3.5'
services:
  db:
    image: postgres:latest
    networks:
      - rinha-network
    container_name: rinhajava2023_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    # DEFINIR REQUISITOS ABAIXO
    # deploy:
  
  api1: &api
    image: rinhajava:latest
    restart: always
    networks:
      - rinha-network
    container_name: rinhajava2023_1
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "6969"
    # deploy:
      # cpus: '0.25'
      # memory: '0.5GB'
  
  api2:
    <<: *api
    container_name: rinhajava2023_2

  nginx:
    image: nginx:latest
    networks:
      - rinha-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    # deploy:
      # resources:
        # limits:
          # cpus: '.1'
          # memory: '50MB'

networks:
  rinha-network:
    # driver: host
    driver: bridge

