version: '3.5'

services:
  db:
    image: postgres:15
    container_name: rinha2023_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    command: -c config_file=/etc/postgresql.conf
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
        - rinha-network
    deploy:
      resources:
        limits:
          cpus: .7
          memory: 1GB

  api1: &api
    image: rinha_sql:latest
    environment:
      - PORT=6969
    restart: always
    container_name: rinha_sql_1
    depends_on:
      db:
        condition: service_healthy
    networks:
        - rinha-network
    deploy:
      resources:
        limits:
          cpus: .2
          memory: 0.5GB
  
  api2:
    <<: *api
    environment:
      - PORT=4200
    container_name: rinha_sql_2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
        - rinha-network
    ports:
      - "9999:9999"
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: .25
          memory: 0.5GB

## LETS TEST VIRTUAL NETWORK vs HOST
networks:
  rinha-network:
    name: rinha-network
    driver: bridge

